name: Build and Push Docker Image

on:
  release:
    types:
      - created

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      if: github.event_name == 'release' && contains(github.event.release.target_commitish, 'refs/tags')
      run: docker login -u ${{ secrets.sushmitapawar }} -p ${{ secrets.dckr_pat_1UHyT63YFHseei2dXyZKy7gijCU }}

    - name: Login to GitHub Container Registry
      if: github.event_name == 'release' && contains(github.event.release.target_commitish, 'refs/tags')
      run: echo "${{ secrets.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 }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      if: github.event_name == 'release' && contains(github.event.release.target_commitish, 'refs/tags')
      run: |
        docker buildx create --use
        docker buildx build -t ghcr.io/${{ github.repository }}:latest -t ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} --file Dockerfile .
        docker push ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
